// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCokRCJ4fnDqo_2FfobRK9a0OVv7BXA2Dc',
    appId: '1:861575802256:web:bf87427309d0f6c230d715',
    messagingSenderId: '861575802256',
    projectId: 'voryn-app',
    authDomain: 'voryn-app.firebaseapp.com',
    storageBucket: 'voryn-app.firebasestorage.app',
    measurementId: 'G-DDPJF19VKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx_7ElDDuFVTFO69fkv4KAs5_d14h7RUo',
    appId: '1:861575802256:android:8cd2112e9465c83b30d715',
    messagingSenderId: '861575802256',
    projectId: 'voryn-app',
    storageBucket: 'voryn-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9ZeL_HkRKKtb5uUg6OotwpORpUotzKKU',
    appId: '1:861575802256:ios:3723991acb9bf54930d715',
    messagingSenderId: '861575802256',
    projectId: 'voryn-app',
    storageBucket: 'voryn-app.firebasestorage.app',
    iosBundleId: 'com.voryn.erp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9ZeL_HkRKKtb5uUg6OotwpORpUotzKKU',
    appId: '1:861575802256:ios:875d1dad810fbea930d715',
    messagingSenderId: '861575802256',
    projectId: 'voryn-app',
    storageBucket: 'voryn-app.firebasestorage.app',
    iosBundleId: 'com.example.bizos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCokRCJ4fnDqo_2FfobRK9a0OVv7BXA2Dc',
    appId: '1:861575802256:web:6ba2beb86320946730d715',
    messagingSenderId: '861575802256',
    projectId: 'voryn-app',
    authDomain: 'voryn-app.firebaseapp.com',
    storageBucket: 'voryn-app.firebasestorage.app',
    measurementId: 'G-8EHRWJFXMW',
  );
}
