import 'package:bizos/features/money_management/domain/entities/money_transaction_entity.dart';
import 'package:bizos/features/money_management/domain/repositories/money_management_repository.dart';
import 'package:bizos/features/money_management/presentation/utils/transaction_event_mapper.dart';
import 'package:intl/intl.dart';

class ShareTransactionStatementUseCase {
  final MoneyManagementRepository repository;

  ShareTransactionStatementUseCase(this.repository);

  Future<String> generateStatementText({
    required MoneyTransactionEntity transaction,
    required bool isPersonal,
    String appName = 'VORYN',
  }) async {
    // Fetch full transaction history sorted from oldest to newest (ascending: true)
    final history = await repository.getTransactionHistory(
      transactionId: transaction.id,
      isPersonal: isPersonal,
      limit: 500,
      offset: 0,
      filterEventType: 'All',
      searchQuery: null,
      ascending: true,
    );

    final currencyFormat = NumberFormat.currency(
      symbol: '₹',
      decimalDigits: 2,
      locale: 'en_IN',
    );
    final dateFormat = DateFormat('dd MMM yyyy');
    final nowDateFormat = DateFormat('dd MMM yyyy');
    final nowTimeFormat = DateFormat('hh:mm a');

    final now = DateTime.now();

    final buffer = StringBuffer();
    buffer.writeln(appName);
    buffer.writeln();
    buffer.writeln('Transaction Statement');
    buffer.writeln();
    buffer.writeln('Customer');
    buffer.writeln(transaction.personName);
    buffer.writeln();
    if (transaction.phone.isNotEmpty) {
      buffer.writeln('Phone');
      buffer.writeln(transaction.phone);
      buffer.writeln();
    }
    buffer.writeln('Status');
    buffer.writeln(transaction.status);
    buffer.writeln();
    buffer.writeln('----------------------------------------');
    buffer.writeln();
    buffer.writeln('Financial Summary');
    buffer.writeln();
    buffer.writeln(
      TransactionEventMapper.getTotalAmountLabel(
        transactionType: transaction.transactionType,
      ),
    );
    buffer.writeln(currencyFormat.format(transaction.amount));
    buffer.writeln();
    buffer.writeln('Total Paid');
    buffer.writeln(currencyFormat.format(transaction.paidAmount));
    buffer.writeln();
    buffer.writeln('Outstanding Balance');
    buffer.writeln(currencyFormat.format(transaction.balanceAmount));
    buffer.writeln();
    buffer.writeln('Due Date');
    buffer.writeln(
      transaction.dueDate != null ? dateFormat.format(transaction.dueDate!) : 'N/A',
    );
    buffer.writeln();
    buffer.writeln('----------------------------------------');
    buffer.writeln();
    buffer.writeln('Transaction History');
    buffer.writeln();

    // Filter out deleted items
    final activeHistory = history.where((h) => h.eventType != 'payment_deleted').toList();

    if (activeHistory.isEmpty) {
      buffer.writeln('No transaction history available.');
      buffer.writeln();
    } else {
      for (int i = 0; i < activeHistory.length; i++) {
        final item = activeHistory[i];
        final eventDate = dateFormat.format(item.createdAt.toLocal());

        buffer.writeln(eventDate);
        buffer.writeln();

        final eventTitle =
            '• ${TransactionEventMapper.formatEventTitle(item.eventType, transactionType: transaction.transactionType)}';

        buffer.writeln(eventTitle);
        buffer.writeln();

        if (item.amount > 0 ||
            item.eventType == 'payment' ||
            item.eventType == 'debt_created' ||
            item.eventType == 'adjustment') {
          buffer.writeln('Amount : ${currencyFormat.format(item.amount)}');
          buffer.writeln();
        }

        if (item.paymentMethod != null && item.paymentMethod!.isNotEmpty) {
          buffer.writeln('Payment Method');
          buffer.writeln(item.paymentMethod);
          buffer.writeln();
        }

        buffer.writeln('Balance After');
        buffer.writeln(currencyFormat.format(item.balanceAfter));
        buffer.writeln();

        final eventDesc = TransactionEventMapper.formatEventDescription(
          item.eventType,
          transactionType: transaction.transactionType,
          notes: item.notes,
        );
        if (eventDesc.isNotEmpty) {
          buffer.writeln('Description');
          buffer.writeln(eventDesc);
          buffer.writeln();
        }

        if (i < activeHistory.length - 1) {
          buffer.writeln('----------------------------------------');
          buffer.writeln();
        }
      }
    }

    buffer.writeln('----------------------------------------');
    buffer.writeln();
    buffer.writeln('Generated by $appName');
    buffer.writeln();
    buffer.writeln('Date');
    buffer.writeln(nowDateFormat.format(now));
    buffer.writeln(nowTimeFormat.format(now));

    return buffer.toString();
  }
}
