import 'package:flutter/material.dart';

/// Report Details card matching the reference UI.
/// Displays selected parameters (Business, Report Type, Date Range, Generated By, Generated At, File Format)
/// and the two action buttons (Export & Print, Share Report).
class ReportDetailsCard extends StatelessWidget {
  final String businessName;
  final String reportType;
  final String dateRange;
  final String generatedBy;
  final String generatedAt;
  final String fileFormat;

  final bool isExporting;
  final VoidCallback onExportAndPrint;
  final VoidCallback onShareReport;

  const ReportDetailsCard({
    super.key,
    required this.businessName,
    required this.reportType,
    required this.dateRange,
    required this.generatedBy,
    required this.generatedAt,
    this.fileFormat = 'PDF',
    required this.isExporting,
    required this.onExportAndPrint,
    required this.onShareReport,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    final cardBg = isDark ? const Color(0xFF111728) : Colors.white;
    final borderColor =
        isDark ? const Color(0xFF1E283D) : const Color(0xFFE2E8F0);
    final iconBg =
        isDark ? const Color(0xFF28254E) : const Color(0xFFEDE9FE);
    final iconColor =
        isDark ? const Color(0xFFA5B4FC) : const Color(0xFF6366F1);
    final labelColor =
        isDark ? const Color(0xFF94A3B8) : const Color(0xFF64748B);
    final valueColor =
        isDark ? const Color(0xFFF8FAFC) : const Color(0xFF0F172A);

    return Container(
      decoration: BoxDecoration(
        color: cardBg,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: borderColor, width: 1),
        boxShadow: [
          BoxShadow(
            color: isDark
                ? Colors.black.withValues(alpha: 0.25)
                : Colors.black.withValues(alpha: 0.03),
            blurRadius: 12,
            offset: const Offset(0, 3),
          ),
        ],
      ),
      padding: const EdgeInsets.all(18.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header: Squircle Eye Icon + Title/Subtitle
          Row(
            children: [
              Container(
                width: 38,
                height: 38,
                decoration: BoxDecoration(
                  color: iconBg,
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Center(
                  child: Icon(
                    Icons.visibility_outlined,
                    size: 20,
                    color: iconColor,
                  ),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Report Details',
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w800,
                        color: valueColor,
                        letterSpacing: -0.2,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      'Review your selected parameters.',
                      style: TextStyle(
                        fontSize: 12,
                        color: labelColor,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),

          const SizedBox(height: 18),
          const Divider(height: 1),
          const SizedBox(height: 16),

          // Parameter Rows
          _buildParamRow(
            icon: Icons.storefront_outlined,
            label: 'Business:',
            value: businessName,
            isDark: isDark,
          ),
          const SizedBox(height: 12),
          _buildParamRow(
            icon: Icons.description_outlined,
            label: 'Report Type:',
            value: reportType,
            isDark: isDark,
          ),
          const SizedBox(height: 12),
          _buildParamRow(
            icon: Icons.calendar_today_outlined,
            label: 'Date Range:',
            value: dateRange,
            isDark: isDark,
          ),
          const SizedBox(height: 12),
          _buildParamRow(
            icon: Icons.person_outline_rounded,
            label: 'Generated By:',
            value: generatedBy,
            isDark: isDark,
          ),
          const SizedBox(height: 12),
          _buildParamRow(
            icon: Icons.access_time_rounded,
            label: 'Generated At:',
            value: generatedAt,
            isDark: isDark,
          ),
          const SizedBox(height: 12),
          _buildParamRow(
            icon: Icons.picture_as_pdf_outlined,
            label: 'File Format:',
            value: fileFormat,
            isDark: isDark,
          ),

          const SizedBox(height: 22),

          // Action Buttons: Export & Print, Share Report
          LayoutBuilder(
            builder: (context, constraints) {
              final isVeryNarrow = constraints.maxWidth < 280;

              final exportBtn = _buildExportButton(isDark);
              final shareBtn = _buildShareButton();

              if (isVeryNarrow) {
                return Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    exportBtn,
                    const SizedBox(height: 10),
                    shareBtn,
                  ],
                );
              }

              return Row(
                children: [
                  Expanded(child: exportBtn),
                  const SizedBox(width: 12),
                  Expanded(child: shareBtn),
                ],
              );
            },
          ),
        ],
      ),
    );
  }

  Widget _buildParamRow({
    required IconData icon,
    required String label,
    required String value,
    required bool isDark,
  }) {
    final labelColor =
        isDark ? const Color(0xFF94A3B8) : const Color(0xFF64748B);
    final valueColor =
        isDark ? const Color(0xFFF8FAFC) : const Color(0xFF0F172A);

    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Left Icon
        Padding(
          padding: const EdgeInsets.only(top: 1.0),
          child: Icon(
            icon,
            size: 16,
            color: labelColor,
          ),
        ),
        const SizedBox(width: 8),

        // Label
        Text(
          label,
          style: TextStyle(
            fontSize: 13,
            fontWeight: FontWeight.w500,
            color: labelColor,
          ),
        ),
        const SizedBox(width: 12),

        // Value (Flexible to wrap gracefully without overflow)
        Expanded(
          child: Text(
            value,
            textAlign: TextAlign.end,
            style: TextStyle(
              fontSize: 13,
              fontWeight: FontWeight.w700,
              color: valueColor,
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildExportButton(bool isDark) {
    return Material(
      color: Colors.transparent,
      child: InkWell(
        onTap: isExporting ? null : onExportAndPrint,
        borderRadius: BorderRadius.circular(14),
        child: Container(
          height: 48,
          decoration: BoxDecoration(
            color: isDark
                ? const Color(0xFF1E1E38)
                : const Color(0xFFF3F0FF),
            borderRadius: BorderRadius.circular(14),
            border: Border.all(
              color: isDark
                  ? const Color(0xFF3F3D6E)
                  : const Color(0xFFDDD6FE),
              width: 1,
            ),
          ),
          alignment: Alignment.center,
          child: isExporting
              ? SizedBox(
                  width: 18,
                  height: 18,
                  child: CircularProgressIndicator(
                    strokeWidth: 2,
                    valueColor: AlwaysStoppedAnimation<Color>(
                      isDark
                          ? const Color(0xFFA5B4FC)
                          : const Color(0xFF6366F1),
                    ),
                  ),
                )
              : Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      Icons.print_outlined,
                      size: 18,
                      color: isDark
                          ? const Color(0xFFA5B4FC)
                          : const Color(0xFF6366F1),
                    ),
                    const SizedBox(width: 8),
                    Flexible(
                      child: Text(
                        'Export & Print',
                        style: TextStyle(
                          fontSize: 13.5,
                          fontWeight: FontWeight.w700,
                          color: isDark
                              ? const Color(0xFFA5B4FC)
                              : const Color(0xFF6366F1),
                        ),
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ],
                ),
        ),
      ),
    );
  }

  Widget _buildShareButton() {
    return Material(
      color: Colors.transparent,
      child: InkWell(
        onTap: isExporting ? null : onShareReport,
        borderRadius: BorderRadius.circular(14),
        child: Container(
          height: 48,
          decoration: BoxDecoration(
            color: const Color(0xFF6366F1),
            borderRadius: BorderRadius.circular(14),
            boxShadow: [
              BoxShadow(
                color: const Color(0xFF6366F1).withValues(alpha: 0.35),
                blurRadius: 10,
                offset: const Offset(0, 3),
              ),
            ],
          ),
          alignment: Alignment.center,
          child: isExporting
              ? const SizedBox(
                  width: 18,
                  height: 18,
                  child: CircularProgressIndicator(
                    strokeWidth: 2,
                    valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                  ),
                )
              : const Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      Icons.share_outlined,
                      size: 18,
                      color: Colors.white,
                    ),
                    SizedBox(width: 8),
                    Flexible(
                      child: Text(
                        'Share Report',
                        style: TextStyle(
                          fontSize: 13.5,
                          fontWeight: FontWeight.w700,
                          color: Colors.white,
                        ),
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ],
                ),
        ),
      ),
    );
  }
}
